name: Build Docker Images

on:
 push:
   branches: [main]
 workflow_dispatch:

env:
 PROJECT_NAME: fds-dockerfiles
 MPI: 1


 build:
   needs: generate-dockerfile-list
   runs-on: ubuntu-latest
   strategy:
     fail-fast: false
   steps:
     - uses: actions/checkout@v3
     
     - name: Set project name
       run: echo "PROJECT_NAME=$(echo $GITHUB_REPOSITORY | sed 's|.*/||')" >> $GITHUB_ENV
     
    #  - name: Copy entrypoint
    #    run: |
    #      DOCKERFILE_DIR=$(dirname ${{ matrix.dockerfile }})
    #      cp ./entrypoint.sh $DOCKERFILE_DIR
     
     - name: Build and Tag
       run: |
         docker build . --tag "$PROJECT_NAME:latest"
         
     - name: Push
       run: |
         echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u ${{ secrets.DOCKERHUB_LOGIN }} --password-stdin
         docker push "$PROJECT_NAME:latest"
